name = "HChebInterp"
uuid = "78faba9b-a54b-441f-8118-62407cbe4e59"
authors = ["lxvm <lorenzo@vanmunoz.com>"]
version = "0.1.2"

[deps]
FastChebInterp = "cf66c380-9a80-432c-aff8-4f9c79c0bdde"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
FastChebInterp = "1"
StaticArrays = "1"
julia = "1.6"
